<?php

namespace uSendit\API;

class BuyCreditsStatus
{
    const __default = 'SUCCESS';
    const SUCCESS = 'SUCCESS';
    const USER_UNKNOWN = 'USER_UNKNOWN';
    const PENDING_SMS_CONFIRMATION_CODE = 'PENDING_SMS_CONFIRMATION_CODE';
    const INVALID_PACK_ID = 'INVALID_PACK_ID';
    const ERROR_GENERATING_PAYMENT_REFERENCE = 'ERROR_GENERATING_PAYMENT_REFERENCE';
    const CALLER_UNKNOWN = 'CALLER_UNKNOWN';
    const MISSING_INVOICE_INFO = 'MISSING_INVOICE_INFO';
    const GENERIC_ERROR = 'GENERIC_ERROR';


}
