<?php

namespace uSendit\API;

class CreateAccountStatusCustom
{
    const __default = 'SUCCESS';
    const SUCCESS = 'SUCCESS';
    const USERNAME_EMPTY = 'USERNAME_EMPTY';
    const USERNAME_NOT_ALLOWED = 'USERNAME_NOT_ALLOWED';
    const USERNAME_EXCEEDS_MAX_LENGTH = 'USERNAME_EXCEEDS_MAX_LENGTH';
    const PASSWORD_EXCEEDS_MAX_LENGTH = 'PASSWORD_EXCEEDS_MAX_LENGTH';
    const PASSWORD_INVALID = 'PASSWORD_INVALID';
    const EMAIL_EXCEEDS_MAX_LENGTH = 'EMAIL_EXCEEDS_MAX_LENGTH';
    const EMAIL_INVALID = 'EMAIL_INVALID';
    const MSISDN_EXCEEDS_MAX_LENGTH = 'MSISDN_EXCEEDS_MAX_LENGTH';
    const MSISDN_INVALID = 'MSISDN_INVALID';
    const MSISDN_ALREADY_IN_USE = 'MSISDN_ALREADY_IN_USE';
    const ACCOUNT_NAME_EMPTY = 'ACCOUNT_NAME_EMPTY';
    const ACCOUNT_NAME_EXCEEDS_MAX_LENGTH = 'ACCOUNT_NAME_EXCEEDS_MAX_LENGTH';
    const ACCOUNT_NAME_NOT_ALLOWED = 'ACCOUNT_NAME_NOT_ALLOWED';
    const CALLER_UNKNOWN = 'CALLER_UNKNOWN';
    const ERROR_SENDING_SMS_CONFIRMATION = 'ERROR_SENDING_SMS_CONFIRMATION';
    const ACCOUNT_VALIDATION_ERROR = 'ACCOUNT_VALIDATION_ERROR';
    const USERNAME_OR_EMAIL_ALREADY_IN_USE = 'USERNAME_OR_EMAIL_ALREADY_IN_USE';
    const ACCOUNT_INFO_EMPTY = 'ACCOUNT_INFO_EMPTY';
    const INVOICE_INFO_EMPTY = 'INVOICE_INFO_EMPTY';
    const INVOICE_INFO_INVALID = 'INVOICE_INFO_INVALID';
    const GENERIC_ERROR = 'GENERIC_ERROR';


}
