<?php

namespace uSendit\API;

class GetScheduleStatusCustom
{
    const __default = 'SCHEDULE_OK';
    const SCHEDULE_OK = 'SCHEDULE_OK';
    const SCHEDULE_OK_WARNING = 'SCHEDULE_OK_WARNING';
    const USER_UNKNOWN = 'USER_UNKNOWN';
    const USER_NOT_ALLOWED = 'USER_NOT_ALLOWED';
    const SMS_LIST_ALL_RECIPIENTS_INVALID = 'SMS_LIST_ALL_RECIPIENTS_INVALID';
    const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
    const SCHEDULE_UNKNOWN = 'SCHEDULE_UNKNOWN';


}
