<?php

namespace uSendit\API;

class ScheduleStatus
{
    const __default = 'SCHEDULE_OK';
    const SCHEDULE_OK = 'SCHEDULE_OK';
    const SCHEDULE_OK_WARNING = 'SCHEDULE_OK_WARNING';
    const USER_UNKNOWN = 'USER_UNKNOWN';
    const USER_PENDING_SMS_CONFIRMATION_CODE = 'USER_PENDING_SMS_CONFIRMATION_CODE';
    const USER_NOT_ALLOWED = 'USER_NOT_ALLOWED';
    const INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS';
    const SMS_LIST_EMPTY = 'SMS_LIST_EMPTY';
    const SMS_LIST_EXCEEDS_MAX_LENGTH = 'SMS_LIST_EXCEEDS_MAX_LENGTH';
    const SMS_LIST_ALL_RECIPIENTS_INVALID = 'SMS_LIST_ALL_RECIPIENTS_INVALID';
    const INTERNAL_CONFIGURATION_ERROR = 'INTERNAL_CONFIGURATION_ERROR';
    const PROCESS_SCHEDULE_LIST_ERROR = 'PROCESS_SCHEDULE_LIST_ERROR';
    const SCHEDULE_ERROR = 'SCHEDULE_ERROR';


}
